Overlord metrics
Tinkoff/overhave pull request #243
Opened 2023-06-19 11:41 UTC by artamaney

2023-06-19 12:49 UTC, lazyevening requested changes

2023-06-19 12:49 UTC, lazyevening commented on overhave/metrics/client/container.py
> +    def _init_gunicorn_metrics(self) -> None:
А эта шляпа из dp точно тут нужна ?

2023-06-19 12:49 UTC, lazyevening commented on overhave/metrics/client/container.py
> +            "gunicorn_current_tasks", "How many tasks is processed right now", registry=self.registry
Тут грамматическая ошибка, причем ниже в _init_product_metrics ты все правильно написал

2023-06-19 12:49 UTC, lazyevening commented on overhave/metrics/client/container.py
> +            "gunicorn_connections", "How many connection is processed right now", registry=self.registry
тут тож

2023-06-19 17:28 UTC, artamaney commented on overhave/metrics/client/container.py
> +    def _init_gunicorn_metrics(self) -> None:
нее давайте дпшную использовать;..

2023-06-19 17:28 UTC, artamaney commented on overhave/metrics/client/container.py
> +    def _init_gunicorn_metrics(self) -> None:
ты прав Артем

2023-06-20 08:02 UTC, livestreamx commented on makefile
> +MIN_COVERAGE ?= 86.78
не, давай не будем опускать

2023-06-20 08:35 UTC, livestreamx commented on overhave/metrics/client/container.py
> +        self._init_product_metrics()
шо за продакт-метрикс? мб просто `_init_metrics`?

2023-06-20 08:38 UTC, livestreamx commented on overhave/metrics/client/container.py
> +
а emulation? давайте тоже сделаем

2023-06-20 08:38 UTC, livestreamx commented on overhave/metrics/client/container.py
> +
я бы там еще порт кидал, чтобы понимать их загрузку (равномерная или нет)

2023-06-21 06:36 UTC, livestreamx commented on overhave/db/tables.py
> +    def __init__(self, emulation_id: int, initiated_by: str, port: int | None = None) -> None:
Давай-ка init выпилим, он не нужен

2023-06-21 06:37 UTC, livestreamx commented on overhave/metrics/client/container.py
> +    def _init_metrics(self) -> None:
А мне кажется, или у нас должны быть разные init на разные части приложения?

2023-06-21 06:39 UTC, livestreamx commented on overhave/admin/views/emulation.py
> +        port = factory.emulation_storage.get_emulation_run_port(emulation_run_id)
А ты в курсе, что у тебя тут порт всегда None? Это нужно на стороне консюмера делать.

2023-06-21 06:40 UTC, livestreamx commented on overhave/storage/emulation_storage.py
> +    def get_emulation_run_port(self, emulation_run_id: int) -> int | None:
Как будто этот парень должен всегда возвращать int. Иначе в чем смысл? Давай переделаем на `emulation_run_port_by_id` и пусть всегда для .one() возвращает int

2023-06-21 06:40 UTC, livestreamx commented on tests/integration/emulation/conftest.py
> +def emulation_settings(mock_envs: None) -> OverhaveEmulationSettings:
На дубликаты в integration/conftest проверил фикстуры?

2023-06-21 13:52 UTC, livestreamx commented on overhave/admin/app.py
> +        METRICS.produce_redis_task(RedisStream.PUBLICATION)
А мы же можем прямо в продюсере тип таски определять - и писать в метрику? Чтобы по коду эти штуки не расставлять

2023-06-21 13:52 UTC, artamaney commented on overhave/admin/app.py
> +        METRICS.produce_redis_task(RedisStream.PUBLICATION)
да можем написать разные методы

2023-06-23 09:19 UTC, livestreamx commented on pyproject.toml
> +version = "3.16.5"
4.0.0 давай

2023-06-26 09:25 UTC, slavrentev approved these changes

2023-06-26 10:40 UTC, SophIren approved these changes

2023-06-26 10:42 UTC, SophIren approved these changes

2023-06-26 10:49 UTC, merged